---
title: "EPIB 676-001 Advanced topics in decision-analytic modeling for health"
subtitle: "Course syllabus, Fall 2023, McGill University"
format:
  html: 
    toc: true
  pdf:
    toc: true
editor: visual
---

```{=html}
<!--
Clicking"render" will only do the first format (html) and delete any other versions (pdf). 
To render both html and pdf, use 

quarto::quarto_render("syllabus/epid-676_syllabus.qmd") 
-->
```
## Course description

Advanced methods used to model health policy decisions and conduct model-based health technology assessment, both theory and technical applications. Methods covered include: Markov and microsimulation models, Bayesian model calibration and evaluation, probabilistic sensitivity analysis, value of information analysis, and equity-informative health policy analysis. Application areas include: disease screening, prevention, and treatment, public health measures, and prioritization of clinical research.

## Learning objectives

By the end of the course, students should be able to:

-   Develop decision analytic models to inform health policy and clinical decisions
-   Understand and critically appraise model-based decision analyses
-   Create transparent reports of model-based decision analyses that conform to open science principles

## Instructor

**W. Alton Russell, PhD**, Assistant Professor, McGill School of Population and Global Health. [alton.russell\@mcgill.ca](alton.russell@mcgill.ca) \| [mchi.mcgill.ca/decision-modeling-lab](mchi.mcgill.ca/decision-modeling-lab) \| Office: 2001 McGill College #1113

## Class sessions & office hours

**Class sessions** will be held 11:35am -- 12:55am on Tuesdays and Thursdays at 2001 McGill College Ave in room #1203. Attendance is required.

**Office hours** will be held 1pm - 2pm in Conference Room #1122 on Tuesdays and Thursdays on days in which class meets. As an exception, office hours will be on Zoom October 17, 19, and 24. Office hours are not just for when students are struggling; all are encouraged to come to discuss assignments and readings.

## Target audience

The course is geared towards PhD students and advanced Masters students interested in conducting model-based analyses of health policies and health technologies in research. Modeling skills developed in the course will also be useful for students interested in industry or government roles related to economic evaluation, policy modeling, health technology assessment, or health economics and outcomes research.

## Prerequisites

The ideal preparation of this course would include (1) an introductory proramming course, (2) a course in probability, (3) a course in statistics, and possibly (4) a course on cost-effectiveness such as PPHS 528. Prior experience programming in R is ideal, but students with solid experience in another programming fundamentals (e.g., nested loops, functions, data structures) should be able to learn the R syntax and environment as they go. Students who lack a prerequisite other than programming may need to spend extra time on some course components but should be able to succeed in the course. The course is likely not appropriate for students missing two or more prerequisites (especially if programming is one of them). To help make an informed decision on how well-prepared you are for the course, you can [attempt to complete assignment 0 early (available on Github)](https://github.com/altonrus/epib-676/tree/main/assignments).

## Readings

Readings drawn from various sources are assigned before most class sessions as indicated in the schedule below. PDFs of the readings are available on MyCourses. Some readings are tutorials with accompanying code, which you are encouraged to download and run. To get full credit for class engagement, students should come to class prepared to discuss the readings.

## Laptops and software

Students should bring a personal laptop to class; please let the instructor know right away if this is a challeng so we can find a solution. Before the first session, students should install and configure the necessary software (R, RStudio, git) [using the 'Setting up your software enviroment' instructions from session 1](https://htmlpreview.github.io/?https://github.com/altonrus/epib-676/blob/main/sessions/01-introduction/get-set-up.html).

## Approach to learning

The course provides hands-on experience applying course concepts early and often. The course has two phases with some overlap:

-   **The methods phase (15 sessions)** focuses on understanding methods and workflows and building programming skills. Readings are primarily pedagogical in nature, including tutorials with accompanied R code you can examine and run. Some class sessions will include running sample code on your own laptop. Six programming assignments will provide hands-on experience in coding a model-based decision analysis.
-   **The application phase (11 sessions)** focuses on the use of decision analytic modeling to inform health policy and clinical practice. You'll be assigned a diverse set of applied modeling analyses as readings, and you'll hear from several decision-analytic modeling analysts in class sessions. Students will also analyze and present an existing open-source modeling study. For the course project, students will develop their own model-based decision analysis.

## Assignments & evaluation

### Class engagement (8%)

Students are expected to attend class on time and prepared to discuss assigned readings. Students should actively engage in discussions, ask questions, and follow along with programming examples on their own laptops.

### R programming assignments (42%)

A series of programming assignments will provide hands-on experience developing decision analytic modeling analyses. For each assignment, students will download a Zip file that contains a Quarto document from the [class Github site](https://github.com/altonrus/epib-676/tree/main/assignments). The Quarto document includes questions, instructions, and starter code. Students will complete the assignments by completing the code and answering questions. Once complete, students will render their Quarto document to an HTML file, which they upload to [MyCourses](https://mycourses2.mcgill.ca/) for grading.

0.  Simpler models (7%)
1.  Decision trees, cost-effectiveness (7%)
2.  Cohort models (7%)
3.  Simulation (7%)
4.  Uncertainty analysis (7%)
5.  Calibration, validation, and value of information (7%)

Out of fairness to your classmates, late assignments will only be accepted in exceptional, clearly-communicated circumstances. All assignments will be available more than one week before their deadline. Recommended best practices for programming assignments:

-   Start early

-   Read the whole assignment before you begin

-   Spend some time on it each day for 3 or more days (instead of completing it in one sitting)

-   Work alone first, then discuss with classmates or the instructor (but you must write your own code and responses)

-   Come to office hours

### Presentation of open-source modeling analysis (10%)

Students will find a published decision-analytic modeling study with open source code. Students will attempt to understand the code run the model on their own machine and give a breif in-class presentation about their experience.

### Course project (40%)

The default course project entails developing a decision-analytic model an use it to inform a decision from health policy or clinical practice. Students are encouraged to analyze a decision problem related to their own research and/or engage with domain experts outside the class when applicable. Other project topics, such as developing or assessing a novel method or using modeling methods for an application that is not a decision analysis, may be approved by the instructor on a case-by-case basic. Students are strongly encouraged to come to office hours to discuss their project with the instructor.

1.  Proposal (2%)
2.  Class presentation (8%)
3.  Written report (with code) (30%)

## Logistics

PDFs of all readings are available to enrolled students in [MyCourses](https://mycourses2.mcgill.ca/). Assignments are due at 11:59pm EST on the date indicated in the schedule below. Grades and feedback will also be provided within MyCourses. All other course materials are available on [Github](https://github.com/altonrus/epib-676), including the assignments.

## Academic integrity

McGill University values academic integrity. Therefore, all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the *Code of Student Conduct and Disciplinary Procedures* ([see here for more details](https://www.mcgill.ca/deanofstudents/students/student-rights-responsibilities/integrity)). Students found guilty of such academic offences will be given a failing grade to this course. 

## Language of submission

In accordance with McGill University's *Charter of Students' Rights*, students have the right to submit any written work that is to be graded in either English or French.

## Course schedule

+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Date**      | **Topics, Readings/tasks to be completed before class** \|                                                                                                                                                                                                                                           |
+===============+======================================================================================================================================================================================================================================================================================================+
| **31 Aug Th** | **1. Course introduction**                                                                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Why do decision analysis                                                                                                                                                                                                                                                                         |
|               | -   Analytic perspective                                                                                                                                                                                                                                                                             |
|               | -   Using R and RStudio                                                                                                                                                                                                                                                                              |
|               | -   **Assignment 0 available (simpler models)**                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | (1) Follow the ['Setting up your software enviroment' instructions](https://htmlpreview.github.io/?https://github.com/altonrus/epib-676/blob/main/sessions/01-introduction/get-set-up.html) to make sure you have an up-to-date local version of R and Rstudio desktop on your laptop.\              |
|               | (2) Read through the [Hello, Quarto tutorial for RStudio](https://quarto.org/docs/get-started/hello/rstudio.html)\                                                                                                                                                                                   |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5 Sep Tu**  | **2. Economic evaluation**                                                                                                                                                                                                                                                                           |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Decision analytic frameworks                                                                                                                                                                                                                                                                     |
|               | -   Quantifying health and costs                                                                                                                                                                                                                                                                     |
|               | -   Incremental analysis                                                                                                                                                                                                                                                                             |
|               | -   **Assignment 1 available (decision trees, cost-effectiveness)**                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                      |
|               | Ch. 1 'Introduction to health economic evaluation' from [*Bayesian Methods in Health Economics (2012) by Gianluca Baio*](https://doi.org/10.1201/b13099)\                                                                                                                                            |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **7 Sep Th**  | **3. Probability, decision trees**                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Conditional probability                                                                                                                                                                                                                                                                          |
|               | -   Distributions, expectation, variance                                                                                                                                                                                                                                                             |
|               | -   Decision trees                                                                                                                                                                                                                                                                                   |
|               | -   **Assignment 0 due Friday**                                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | Ch 9, pg 311 - 351 (you can skip 9.4.5 -- 9.4.7, pg 331 - 338) 'Economic evaluation using decision-analytic modelling' from [*'Methods for the Economic Evaluation of Health Care Programmes' (2014) by Drummond et. al.*](http://ebookcentral.proquest.com/lib/mcgill/detail.action?docID=4605509)\ |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **12 Sep Tu** | **4. Cohort models I**                                                                                                                                                                                                                                                                               |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Discrete time state-transition models                                                                                                                                                                                                                                                            |
|               | -   Markov model solution                                                                                                                                                                                                                                                                            |
|               | -   Time-varying transitions                                                                                                                                                                                                                                                                         |
|               | -   **Assignment 2 available (cohort models)**                                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Alarid Escudero et. al. 2022. An introductory tutorial on cohort state-transition models in R using a cost-effectiveness analysis example*](https://doi.org/10.1177/0272989X221103163)\                                                                                                            |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **14 Sep Th** | **5. Cohort models II**                                                                                                                                                                                                                                                                              |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Capturing health-economic outcomes                                                                                                                                                                                                                                                               |
|               | -   Discrete time error corrections                                                                                                                                                                                                                                                                  |
|               | -   Capturing epidemiological outcomes                                                                                                                                                                                                                                                               |
|               | -   Differential equation models                                                                                                                                                                                                                                                                     |
|               | -   **Assignment 1 due Friday**                                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Alarid Escudero et. al. 2022. A tutorial on time-dependent cohort state-transition models in R using a cost-effectiveness analysis example*](https://doi.org/10.1177/0272989X221121747)\                                                                                                           |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **19 Sep Tu** | **6. Simulation I**                                                                                                                                                                                                                                                                                  |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Monte Carlo simulation                                                                                                                                                                                                                                                                           |
|               | -   Simulating decision trees                                                                                                                                                                                                                                                                        |
|               | -   Simulating state transition models                                                                                                                                                                                                                                                               |
|               | -   **Assignment 3 available (simulation)**                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Krijkamp et. al. 2018. Microsimulation modeling for health decision sciences Using R: A tutorial*](http://www.doi.org/10.1177/0272989X18754513)                                                                                                                                                    |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **21 Sep Th** | **7. Simulation II**                                                                                                                                                                                                                                                                                 |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Efficient coding practices                                                                                                                                                                                                                                                                       |
|               | -   Efficiency techniques for simulation                                                                                                                                                                                                                                                             |
|               |                                                                                                                                                                                                                                                                                                      |
|               | Sections 1.4 and Ch. 2 (pg. 15 - 17, 23 - 64) from [*Discrete Event Simulation for Health Technology Assessment (2016) by Caro et. al.*](https://www.routledge.com/Discrete-Event-Simulation-for-Health-Technology-Assessment/Caro-Moller-Karnon-Stahl-Ishak/p/book/9780367737689)                   |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **26 Sep Tu** | **8. Simulation III**                                                                                                                                                                                                                                                                                |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Discrete even simulation                                                                                                                                                                                                                                                                         |
|               | -   Agent based models                                                                                                                                                                                                                                                                               |
|               | -   Network model models                                                                                                                                                                                                                                                                             |
|               | -   **Assignment 2 due Wednesday**                                                                                                                                                                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Chhatwal & He (2015). Economic evaluations with agent-based modelling: An introduction.*](https://doi.org/10.1007/s40273-015-0254-2)\                                                                                                                                                              |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **28 Sep Th** | **9. Uncertainty analysis**                                                                                                                                                                                                                                                                          |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Probabilistic sensitivity analysis                                                                                                                                                                                                                                                               |
|               | -   Credible intervals                                                                                                                                                                                                                                                                               |
|               | -   Univariate sensitivity analysis                                                                                                                                                                                                                                                                  |
|               | -   Scenario analysis                                                                                                                                                                                                                                                                                |
|               | -   **Assignment 4 available (Sensitivity analysis)**                                                                                                                                                                                                                                                |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Briggs et. al. 2012. Model parameter estimation and uncertainty analysis: ISPOR-SMDM modeling good practices task force report*](https://doi.org/10.1177/0272989X12458348)                                                                                                                         |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **3 Oct Tu**  | **10. Designing & parameterizing an analysis**                                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Perspective, time horizons, comparators                                                                                                                                                                                                                                                          |
|               | -   Deciding on scope & structure                                                                                                                                                                                                                                                                    |
|               | -   Literature-based inputs                                                                                                                                                                                                                                                                          |
|               | -   Patient-level data inputs                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | (1) [*Roberts et. al. 2012. Conceptualizing a model: a report of the ISPOR-SMDM Modeling Good Research Practices Task Force*](https://doi.org/10.1016/j.jval.2012.06.016)                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                                      |
|               | (2) Ch 8 (pg 209 - 236) 'Finding and summarizing the evidence' from [*Decision Making in Health and Medicine (2014) by Hunink et. al.*](https://doi.org/10.1017/CBO9781139506779.011)                                                                                                                |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5 Oct Th**  | **11. Modeling workflow**                                                                                                                                                                                                                                                                            |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Open science practices                                                                                                                                                                                                                                                                           |
|               | -   An R project workflow                                                                                                                                                                                                                                                                            |
|               | -   Version control                                                                                                                                                                                                                                                                                  |
|               | -   **Assignment 3 due Wednesday**                                                                                                                                                                                                                                                                   |
|               | -   **Project proposal assigned**                                                                                                                                                                                                                                                                    |
|               | -   **Open-source model presentation assigned**                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Eddy et. al. 2012. Model transparency and validation: ISPOR-SMDM modeling good practices task force report*](https://www.doi.org/10.1177/0272989X12454579)                                                                                                                                         |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **8 Oct Tu**  | *Thanksgiving break, no class*                                                                                                                                                                                                                                                                       |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **12 Oct Th** | **12. Calibration & validation**                                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Bayesian model calibration                                                                                                                                                                                                                                                                       |
|               | -   Model validation                                                                                                                                                                                                                                                                                 |
|               | -   **Assignment 5 available (calibration, validation, VoI)**                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [*Menzies et. al. 2017. Bayesian methods for calibrating health policy models: A tutorial.*](https://www.doi.org/10.1007/s40273-017-0494-4)                                                                                                                                                          |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **17 Oct Tu** | **13. Guest lecture:** "Outbreaks of COVID-19 variants in US prisons: a mathematical modelling analysis of vaccination and reopening policies" by Theresa Ryckman, PhD (Johns Hopkins University)                                                                                                    |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Office hours on Zoom only                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1016/S2468-2667(21)00162-6 "https://doi.org/10.1016/S2468-2667(21)00162-6"), Code to be posted on MyCourses                                                                                                                                                          |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **19 Oct Th** | **14. Guest lecture:** \"Estimating the impact of low influenza activity in 2020 on population immunity and future influenza seasons in the United States" by Kyueun Lee, PhD (University of Washington)                                                                                             |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Office hours on Zoom only                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1093/ofid/ofab607), [Code](https://github.com/noyarim/Influenza-VOI)                                                                                                                                                                                                 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **24 Oct Tu** | **15. Guest lecture:** "Modeling the impact of federal interventions to reduce harms of the opioid crisis in Canada" by Dimitra Panagiotoglou, PhD and Mariam El Sheikh, MSc (McGill)                                                                                                                |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Office hours on Zoom only                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1093%2Fepirev%2Fmxab013)                                                                                                                                                                                                                                             |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **26 Oct Th** | **16. Student presentations of open-source modeling analyses**                                                                                                                                                                                                                                       |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   **Project proposal due Monday**                                                                                                                                                                                                                                                                  |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **31 Oct Tu** | **17. Value of information analysis**                                                                                                                                                                                                                                                                |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   For research prioritization and as sensitivity analysis                                                                                                                                                                                                                                          |
|               | -   VOI measures (EVPI, EVPPI, EVSI)                                                                                                                                                                                                                                                                 |
|               | -   Challenges and limitation                                                                                                                                                                                                                                                                        |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Fenwick et. al. 2020. Value of information analysis for research decisions---an introduction: Report 1 of the ISPOR Value of Information Analysis Emerging Good Practices Task Force](https://doi.org/10.1016/j.jval.2020.01.001)                                                                   |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **2 Nov Th**  | **18. Statistical and machine learning modeling**                                                                                                                                                                                                                                                    |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Time-to-event models                                                                                                                                                                                                                                                                             |
|               | -   Competing events                                                                                                                                                                                                                                                                                 |
|               | -   Temporal extrapolation                                                                                                                                                                                                                                                                           |
|               | -   Machine learning                                                                                                                                                                                                                                                                                 |
|               | -   **Assignment 4 due Friday**                                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | Reading TBD                                                                                                                                                                                                                                                                                          |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **7 Nov Tu**  | **19. Equity and distributional considerations**                                                                                                                                                                                                                                                     |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   Evaluation frameworks                                                                                                                                                                                                                                                                            |
|               | -   Estimating heterogeneity                                                                                                                                                                                                                                                                         |
|               |                                                                                                                                                                                                                                                                                                      |
|               | (1) [*Avanceña and Prosser (2021). Innovations in cost-effectiveness analysis that advance equity can expand its use in health policy*](https://doi.org/10.1136/bmjgh-2021-008140)                                                                                                                   |
|               |                                                                                                                                                                                                                                                                                                      |
|               | (2) [*Love-Koh et. al. (2019). Aggregate distributional cost-effectiveness analysis of health technologies*](https://doi.org/10.1016/j.jval.2019.03.006)                                                                                                                                             |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **9 Nov Th**  | **20. Guest lecture:** "Costs, quality-adjusted life years, and value-of-information of different thresholds for the initiation of invasive ventilation in hypoxemic respiratory failure" by Christopher Yarnell, MD (University of Toronto / University Health Network)                             |
|               |                                                                                                                                                                                                                                                                                                      |
|               | -   **Assignment 5 due Friday**                                                                                                                                                                                                                                                                      |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1101/2023.03.16.23286754), [Code](https://github.com/cjyarnell/IMVthresholds_HealthEconomicEvaluation)                                                                                                                                                               |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **14 Nov Tu** | **21. Guest lecture:** "Extended Cost-Effectiveness Analysis (ECEA) and priority setting (with a case study of human papillomavirus vaccination in Ethiopia)" by Allison Portnoy, PhD (Boston University)                                                                                            |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1093/heapol/czab052)                                                                                                                                                                                                                                                 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **16 Nov Th** | **22 Guest lecture:** "Model-Estimated Association Between Simulated US Elementary School--Related SARS-CoV-2 Transmission, Mitigation Interventions, and Vaccine Coverage Across Local Incidence Levels" by John Giardina, PhD (Mass General Research Institute/Harvard University)                 |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1001/jamanetworkopen.2021.47827), [Code](https://github.com/abilinski/BackToSchool2/tree/master/3%20-%20Scripts/Paper%203), additional resource on code debugging to be added later.                                                                                 |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **21 Nov Tu** | **23. Guest lecture:** "Re-evaluating the health impact and cost-effectiveness of tuberculosis preventive treatment for modern HIV cohorts on antiretroviral therapy: a modelling analysis using data from Tanzania" by Jinyi Zhu, PhD (Vanderbilt University)                                       |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1016/S2214-109X(22)00372-2), [Code](https://github.com/jinyizhu/IPTinTZ)                                                                                                                                                                                             |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **23 Nov Th** | **24. Guest lecture:** "The diagonal approach: A theoretic framework for the economic evaluation of vertical and horizontal interventions in healthcare" by Erin Kirwin, MSc (Institute of Health Economics, Alberta and University of Manchester)                                                   |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://doi.org/10.1016/j.socscimed.2022.114900), [Code](https://github.com/erinkirwin/diagonal-approach)                                                                                                                                                                               |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **28 Nov Tu** | **25. Guest lecture:** "Effect of increased alcohol consumption during COVID‐19 pandemic on alcohol‐associated liver disease: A modeling study" by Jovan Julien, PhD (Mass General Institute for Technology Assessment / Harvard Medical School)                                                     |
|               |                                                                                                                                                                                                                                                                                                      |
|               | [Manuscript](https://www.doi.org/10.1002/hep.32272), Code to be posted on MyCourses                                                                                                                                                                                                                  |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **5 Dec Tu**  | **26. Final presentations and wrap-up lecture**\                                                                                                                                                                                                                                                     |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **13 Dec We** | Final project report + code due on MyCourses (no class)\                                                                                                                                                                                                                                             |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Course schedule {.bordered .hover tbl-colwidths="\[15,85\]"}
