---
title: "Info for non-programming assignments"
author: "Alton Russell"
date: today
format:
  html:
    toc: true
editor: visual
---

## **Open-source modeling study presentation (8% final grade)**

Students will find a published decision-analytic modeling study that also provides open source code in R (or another language with which the student is comfortable). Students will read the paper, review the code, and attempt to run it themselves (no need to spend over 2 hours analyzing the code; it's OK if you don't get it running). Students will give a high level class presentation about the paper with a focus on the question being answered, methodological approach, and reproducibility.

-   Oral presentation with slides is the only deliverable (no written report)

-   No more than 12 slides and 8 minutes

-   When you select your paper, post the citation on the MyCourses discussion forum to make sure each student has a unique paper

### Finding a paper

Because most publications still don't publish their code open source, it may be easier to search for a code repositories then finding the paper, rather than searching for papers then checking if the code are publised. You can search general code repositories like [Zenodo.org](https://zenodo.org/) or [OSF.io](https://www.OSF.io). You can also check out the [Global Health CEA open-source model clearinghouse](http://ghcearegistry.org/orchard/open-source-model-clearinghouse) and [SMDM COVID-19 modeling repository](https://smdm.org/news/detail/smdm-covid-19-modeling-special-committee-creating-a-platform-for-collaborat). Since many authors will share code via a Github link, you can also search Google scholar for your topic and the word 'Github'.

### Your presentation should address

-   Why did you pick this paper?

-   In brief, what is the decision problem, setting, alternatives, perspective, time horizon, key findings?

-   What modeling method was used? What do you think of the choice?

-   In terms of reproducibility, what was done well? What could have been better?

### Assessment criteria

Do the oral presentation and slides:

-   Succinctly address all points above?

-   Demonstrate understanding of decision-analytic modeling?

-   Demonstrate understanding of reproducible research and reporting?

## Course project (36% final grade)

Students will develop their own decision-analytic model and use it to analyze a decision related to health policy or clinical practice. The project should demonstrate all major components of a decision analysis: a choice between alternatives with trade-offs, a decision framework/objective (e.g., cost minimization, comparative effectiveness, cost-effectiveness), inputs from appropriate sources, a working model that produces outputs, and uncertainty analysis. Students are encouraged to analyze a decision problem related to their research or professional interests. Students are welcome to engage with domain experts outside the class, such as thesis supervisors or collaborators. A thorough and accurate analysis is [**not**]{.underline} expected; several aspects of the analysis can be simplified compared to what would be submitted to a peer-reviewed journal. It's suggested that you get a simple model working quickly, even if the parameters are completely fictitious, and then refine it. Students may re-purpose others' code or use any packages for developing models, as long as all sources are appropriately acknowledged and cited.

**Note on assessment:** An analysis for peer reviewed publication should include high-quality parameters sourced from the best available data, a model that is complex enough to capture the key decision trade-offs, and thorough uncertainty analysis. To complete the course project in the allotted time, you will need to make simplifications. When grading, I will not penalize you for simplifications as long as (A) your report demonstrates an understanding of what more would need to be done to reach a "publication worthy" analysis, and (B) taken as a whole, the amount of work done is appropriate (you haven't overly simplified everything). It's up to you which parts of the analysis are more or less simplified. You are encouraged to spend more time on components of the project that most interests you. If you have questions about what is "enough", talk to me!

While a (simplified) applied decision analysis is the default project type, other ideas may be considered on a case-by-case basis but must be approved by the instructor before the project proposal deadline.

### Project proposal (2% final grade)

This should be about one page, and feel free to use bullet points. The aim is to make sure you have identified an appropriate decision to model and have done some initial reading and thinking to assess feasibility. You are not "locked in" to the analysis you put in the project proposal.

The proposal should contain your initial plans with respect to your:

-   Decision problem to model

-   Alternatives to evaluate (at least two)

-   Analytic framework (e.g., cost minimization, comparative effectiveness, cost-utility)

-   Modeling method

-   Planned approach for model parameterization (e.g., secondary literature sources, analysis of primary data, or some combination thereof. In most cases, unless the project is tied to your research, students rely on secondary literature sources for parameters)

If your project is in collaboration with others and/or builds on work you began before this semester, please describe this context. Make it clear what components of the larger project are being newly developed this semester by you for the class project.

### Project report with code (26% final grade)

It is recommended that you write the report as a 'literate programming' document with Quarto and render to an HTML, PDF, or Word document (I'll grade any of them). Please include tables and figures in-line, rather than at the end. The length [**should not exceed**]{.underline} 3,500 words, the length of a typical peer reviewed manuscript in a medical journal, not including references or code. There is no lower limit on length, and concision is appreciated. Your report should describe your analysis but also engage with peer-reviewed literature, citing works related to the decision problem modeled and any works from which parameter values or methods were derived.

Here is an outline of the recommended sections and what should be included in each. Sub-headers are encouraged.

#### Background

-   What is the decision problem your model aims to inform?

-   What is already known, and what are the key questions you hope to address?

-   Why is this important?

#### Method

-   What is your analytic design, setting, outcome(s) estimated, alternatives, population, time horizon?

-   How is your model structured, and what dynamics or quantities are captured?

-   What simplifications have you made to the model?

-   What data (primary data and/or secondary data derived from published reports) are you using to parameterize or calibrate your model? It is a good practice to include a parameter table in the method section.

-   What uncertainty analysis are you conducting?

#### Results

-   What are the main findings, based on your possibly flawed model? You should estimate outcomes for \>1 alternative and, if using a cost-effectiveness framework, conduct incremental analysis (compute ICERS).

-   What was the result of your uncertainty analysis?

#### Expansion plan

-   If you were to develop your class project into a complete analysis you could submit for peer reviewed publication, what are the main things you would enhance or add? You may use a bulleted list.

#### Discussion

-   What are the key takeaways from your initial analysis (and/or, what might the takeaways be if a more complete analysis was conducted)?

-   What is the relationship between your findings and the wider literature and/or policy landscape?

-   Beyond those discussed in the expansion plan, what are the strengths and limitations of your approach?

#### Assessment

I will assess reports and code based on:

-   **Scope and clarity:** Do the text, tables, and figures clearly and cohesively identify and inform a decision problem? Are the expectations for each section of the report (outlined above) clearly addressed?

-   **Design choices:** Does the analysis provide insight into a relevant decision problem using fit-for-purpose methods, assumptions, and data inputs? Does the 'expansion plan' demonstrate an understanding of what would be appropriate and feasible for a publication-worthy analysis?

-   **Integration of knowledge:** Is the peer-reviewed literature meaningfully engaged to inform the analysis (borrowing of methods or assumptions, parameterization, and/or calibration) and to contextualize the decision-problem and findings?

### Project presentation (8% final grade)

Presentations (no more than 10 minutes) should give a high-level picture of the project including: why you chose your topic, what modeling work you did, and what your findings could mean for clinical practice or health policy. Students should have some results to present at the time of the presentation, but they do not need to be complete or final. Feedback from the presentation can be used to make adjustments to the final report before it is turned in.

#### Assessment

I will assess presentations based on:

-   **Clarity:** Was the presentation easy to follow, logically ordered, and smoothly presented?

-   **Level of detail:** Did the presenter(s) make the motivation, methods, and key takeaways clear without going into excessive detail or going over the allotted time?

-   **Preparedness:** Has the presenter made substantial progress on the project, which include at least preliminary results? Did the presenter handle audience questions well?
